approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

packageExtensions:
  eslint-plugin-n@*:
    peerDependencies:
      typescript: "*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - linux
    - darwin
